import time

x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')
time.sleep(5)
x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')
time.sleep(5)
x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')
time.sleep(5)
x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')
time.sleep(5)
x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')
time.sleep(5)
x = time.time()
print(f'Segundos: {x}')
print(f'Local time: {time.ctime(x)}')